---
categories:
- ""
- ""
date: "2017-10-31T22:42:51-05:00"
description: London bike usage analysis
image: pic012.jpg
keywords: ""
slug: blog8
title: Social media survey
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />


<div id="general-social-survey-gss" class="section level1">
<h1>General Social Survey (GSS)</h1>
<p>Social media plays a big role in our life. Lets get to understand the demographics of social media users more!
The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviours, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.</p>
<p>First lets load some libraries:</p>
<pre class="r"><code>library(tidyverse) #load libraries</code></pre>
<pre><code>## -- Attaching packages ------------------------------------------------------------------------------------------------------------- tidyverse 1.3.0 --</code></pre>
<pre><code>## v ggplot2 3.3.2     v purrr   0.3.4
## v tibble  3.0.3     v dplyr   1.0.2
## v tidyr   1.1.2     v stringr 1.4.0
## v readr   1.3.1     v forcats 0.5.0</code></pre>
<pre><code>## -- Conflicts ---------------------------------------------------------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(mosaic)</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Loading required package: ggformula</code></pre>
<pre><code>## Loading required package: ggstance</code></pre>
<pre><code>## 
## Attaching package: &#39;ggstance&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:ggplot2&#39;:
## 
##     geom_errorbarh, GeomErrorbarh</code></pre>
<pre><code>## 
## New to ggformula?  Try the tutorials: 
##  learnr::run_tutorial(&quot;introduction&quot;, package = &quot;ggformula&quot;)
##  learnr::run_tutorial(&quot;refining&quot;, package = &quot;ggformula&quot;)</code></pre>
<pre><code>## Loading required package: mosaicData</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;mosaic&#39;:
##   method                           from   
##   fortify.SpatialPolygonsDataFrame ggplot2</code></pre>
<pre><code>## 
## The &#39;mosaic&#39; package masks several functions from core packages in order to add 
## additional features.  The original behavior of these functions should not be affected by this.
## 
## Note: If you use the Matrix package, be sure to load it BEFORE loading mosaic.
## 
## Have you tried the ggformula package for your plots?</code></pre>
<pre><code>## 
## Attaching package: &#39;mosaic&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:Matrix&#39;:
## 
##     mean</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     count, do, tally</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     cross</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     stat</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,
##     quantile, sd, t.test, var</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     max, mean, min, prod, range, sample, sum</code></pre>
<pre class="r"><code>library(ggthemes)</code></pre>
<pre><code>## 
## Attaching package: &#39;ggthemes&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:mosaic&#39;:
## 
##     theme_map</code></pre>
<pre class="r"><code>library(lubridate)</code></pre>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     date, intersect, setdiff, union</code></pre>
<pre class="r"><code>library(fivethirtyeight)</code></pre>
<pre><code>## Some larger datasets need to be installed separately, like senators and
## house_district_forecast. To install these, we recommend you install the
## fivethirtyeightdata package by running:
## install.packages(&#39;fivethirtyeightdata&#39;, repos =
## &#39;https://fivethirtyeightdata.github.io/drat/&#39;, type = &#39;source&#39;)</code></pre>
<pre class="r"><code>library(here)</code></pre>
<pre><code>## here() starts at C:/Users/NOOR/Documents/R/PortfolioNoorA</code></pre>
<pre class="r"><code>library(skimr)</code></pre>
<pre><code>## 
## Attaching package: &#39;skimr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:mosaic&#39;:
## 
##     n_missing</code></pre>
<pre class="r"><code>library(janitor)</code></pre>
<pre><code>## 
## Attaching package: &#39;janitor&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     chisq.test, fisher.test</code></pre>
<pre class="r"><code>library(vroom)
library(tidyquant)</code></pre>
<pre><code>## Loading required package: PerformanceAnalytics</code></pre>
<pre><code>## Loading required package: xts</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre><code>## 
## Attaching package: &#39;xts&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     first, last</code></pre>
<pre><code>## 
## Attaching package: &#39;PerformanceAnalytics&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     legend</code></pre>
<pre><code>## Loading required package: quantmod</code></pre>
<pre><code>## Loading required package: TTR</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<pre><code>## Version 0.4-0 included new data defaults. See ?getSymbols.</code></pre>
<pre><code>## == Need to Learn tidyquant? ==========================================================================================================================
## Business Science offers a 1-hour course - Learning Lab #9: Performance Analysis &amp; Portfolio Optimization with tidyquant!
## &lt;/&gt; Learn more at: https://university.business-science.io/p/learning-labs-pro &lt;/&gt;</code></pre>
<pre class="r"><code>library(kableExtra)</code></pre>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
<pre class="r"><code>library(broom)
library(GGally)</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<pre class="r"><code>library(infer)</code></pre>
<pre><code>## 
## Attaching package: &#39;infer&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:mosaic&#39;:
## 
##     prop_test, t_test</code></pre>
<pre class="r"><code>library(huxtable)</code></pre>
<pre><code>## 
## Attaching package: &#39;huxtable&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:GGally&#39;:
## 
##     wrap</code></pre>
<pre><code>## The following object is masked from &#39;package:kableExtra&#39;:
## 
##     add_footnote</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     add_rownames</code></pre>
<pre><code>## The following object is masked from &#39;package:ggplot2&#39;:
## 
##     theme_grey</code></pre>
<p>Let’s load this intersting data for the year 2016:</p>
<pre class="r"><code>gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;, &quot;NA&quot;))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   emailmin = col_double(),
##   emailhr = col_double(),
##   snapchat = col_character(),
##   instagrm = col_character(),
##   twitter = col_character(),
##   sex = col_character(),
##   degree = col_character()
## )</code></pre>
<p>The variables we have in our data are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media (in 2016)</li>
<li><code>sex</code>: Female or Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>We will now estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016:</p>
<pre class="r"><code># calculate snap_insta, that measures Instagram and Snapchat use in combination
snap_insta_df &lt;- gss %&gt;%
  # &quot;Yes&quot; if the respondent reported using any of snapchat or instagrm, and &quot;No&quot; if not. If both NA then also NA.
  mutate(snap_insta = case_when(snapchat == &quot;Yes&quot; | instagrm == &quot;Yes&quot; ~ &quot;Yes&quot;,
                                is.na(snapchat) &amp; is.na(instagrm) ~ NA_character_ ,
                                TRUE ~ &quot;No&quot;)
         )

# print overall proportion
snap_insta_df %&gt;%
  summarise(`number of instagram/ snapchat users` = count(snap_insta == &quot;Yes&quot;),
            `number of people who use neither` = count(snap_insta == &quot;No&quot;),
            `proportion of instagram/ snapchat users` = count(snap_insta == &quot;Yes&quot;)/count(snap_insta %in% c(&quot;Yes&quot;,&quot;No&quot;))) %&gt;%
  kbl() %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;)) # have a nice HTML table</code></pre>
<pre><code>## Warning: `data_frame()` is deprecated as of tibble 1.1.0.
## Please use `tibble()` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_warnings()` to see where this warning was generated.</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
number of instagram/ snapchat users
</th>
<th style="text-align:right;">
number of people who use neither
</th>
<th style="text-align:right;">
proportion of instagram/ snapchat users
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
514
</td>
<td style="text-align:right;">
858
</td>
<td style="text-align:right;">
0.3746356
</td>
</tr>
</tbody>
</table>
<p>Hence, our best guess is that overall 37.5% of the whole population use instagram, snapchat, or both.</p>
<p>But it’s always better to not always look at point estimates, but at confidence intervals. As we are also interested in the difference between men and women, we calculate two CIs - on for men, one for women - for the snapchat / instagram proportion with traditional mathematical formulas:</p>
<pre class="r"><code># calculate CIs for men and women
sex_formula_ci &lt;- snap_insta_df %&gt;%
  filter(!is.na(snap_insta)) %&gt;% 
  group_by(sex) %&gt;%  # group by sex and calculate CIs
  summarise(`proportion of instagram/ snapchat users` = count(snap_insta == &quot;Yes&quot;)/count(snap_insta %in% c(&quot;Yes&quot;,&quot;No&quot;)),
            z_critical = qnorm(0.975),
            count = n(),
            # Confidence Interval for proportion = p  +/-  z*(√p(1-p) / n)
            se_proportion = sqrt((`proportion of instagram/ snapchat users`*(1-`proportion of instagram/ snapchat users`))/count),
            margin_of_error = z_critical * se_proportion,
            `lower bound` = `proportion of instagram/ snapchat users` - margin_of_error,
            `upper bound` = `proportion of instagram/ snapchat users` + margin_of_error
  )</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre class="r"><code># print table with CIs
sex_formula_ci %&gt;%
  select(sex, `lower bound`, `proportion of instagram/ snapchat users`, `upper bound`) %&gt;% # only show relevant columns
  kbl(caption = &quot;confidence interval on proportion of instagram/snapchat users by sex&quot;) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;)) # have a nice HTML table</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:snap_insta_CI)confidence interval on proportion of instagram/snapchat users by sex
</caption>
<thead>
<tr>
<th style="text-align:left;">
sex
</th>
<th style="text-align:right;">
lower bound
</th>
<th style="text-align:right;">
proportion of instagram/ snapchat users
</th>
<th style="text-align:right;">
upper bound
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Female
</td>
<td style="text-align:right;">
0.3838566
</td>
<td style="text-align:right;">
0.4187256
</td>
<td style="text-align:right;">
0.4535947
</td>
</tr>
<tr>
<td style="text-align:left;">
Male
</td>
<td style="text-align:right;">
0.2812250
</td>
<td style="text-align:right;">
0.3184080
</td>
<td style="text-align:right;">
0.3555909
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># plot CIs
ggplot(sex_formula_ci, aes(y=sex, x = `proportion of instagram/ snapchat users`, group = sex, color=sex)) +
  #draws the means
  geom_point(size = 5) +
  #draws the CI error bars
  geom_errorbar(aes(xmin=`lower bound`, xmax=`upper bound`), width=.1, size = 2) +
  theme_bw() +
  theme(legend.position = &quot;none&quot;)+
  labs(title = &quot;Women Spend More Hours on Social Media&quot;,
       subtitle = &quot;Confidence Intervals of Instagram/Snapchat Usage&quot;)</code></pre>
<p><img src="/blogs/blog8_files/figure-html/snap_insta_CI-1.png" width="672" /></p>
<p>We can clearly see that the data supports the view that many more women use instagram and snapchat than men do!</p>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>Wait, there is a another social media, for which we have data! Let’s have a look at Twitter! What do you think bachelor and graduate students’ usage of Twitter would be?</p>
<p>To find out, we have to clean the data first.</p>
<p>First, let’s turn <code>degree</code> from a character variable into a factor variable, in ascending order of years of education (Lt high school, High School, Junior college, Bachelor, Graduate).</p>
<p>We then create a new variable, <code>bachelor_graduate</code>, that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree, in order to distinguish bachelor/graduate students from others.</p>
<pre class="r"><code># #inspect distinct value of degree
# gss %&gt;%
#   select(degree) %&gt;%
#   distinct(degree)

gss_modify &lt;- gss %&gt;%
  # make degree a factor with the right ordering
  mutate(degree = factor(degree,level=c(&quot;Lt high school&quot;,
                                        &quot;High school&quot;,
                                        &quot;Junior college&quot;,
                                        &quot;Bachelor&quot;,
                                        &quot;Graduate&quot;)),
         # create bachelor_graduate variable
         bachelor_graduate = case_when(degree %in% c(&quot;Bachelor&quot;,&quot;Graduate&quot;) ~ &quot;Yes&quot;,
                                       is.na(degree) ~ NA_character_,
                                       TRUE ~ &quot;No&quot;)
         )</code></pre>
<p>Third, let’s calculate the overall proportion of Twitter users:</p>
<pre class="r"><code>gss_modify %&gt;% 
  # drop observations that miss information
  drop_na(c(bachelor_graduate,twitter)) %&gt;% 
  # calculate overall Twitter proportion
  summarise(`people who use Twitter` = count(twitter == &quot;Yes&quot;),
            `people who don&#39;t use Twitter` = count(twitter == &quot;No&quot;),
            `proportion of those who use Twitter` = `people who use Twitter` / (`people who use Twitter` + `people who don&#39;t use Twitter`),
            `proportion of those who don&#39;t use Twitter` = 1 - `proportion of those who use Twitter`) %&gt;%
  kbl(caption = &quot;Overall Proportion of Twitter users&quot;) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;)) # have a nice HTML table</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:bachelor_graduate_prop_2)Overall Proportion of Twitter users
</caption>
<thead>
<tr>
<th style="text-align:right;">
people who use Twitter
</th>
<th style="text-align:right;">
people who don’t use Twitter
</th>
<th style="text-align:right;">
proportion of those who use Twitter
</th>
<th style="text-align:right;">
proportion of those who don’t use Twitter
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
255
</td>
<td style="text-align:right;">
1116
</td>
<td style="text-align:right;">
0.1859956
</td>
<td style="text-align:right;">
0.8140044
</td>
</tr>
</tbody>
</table>
<p>Let’s now bring in our newly created variable <code>bachelor_graduate</code> and see how Twitter usage varies between those with a degree vs those without a degree:</p>
<pre class="r"><code>gss_modify %&gt;% 
  # drop observations that miss information
  drop_na(c(bachelor_graduate,twitter)) %&gt;% 
  group_by(bachelor_graduate) %&gt;% # group by bachelor_graduate and calculate proportions of Twitter users
  rename(`have a higher educational degree?` = bachelor_graduate) %&gt;% # have a readable name
  summarise(`people who use Twitter` = count(twitter == &quot;Yes&quot;),
            `people who don&#39;t use Twitter` = count(twitter == &quot;No&quot;),
            `proportion of those who use Twitter` = `people who use Twitter` / (`people who use Twitter` + `people who don&#39;t use Twitter`),
            `proportion of those who don&#39;t use Twitter` = 1 - `proportion of those who use Twitter`) %&gt;%
  kbl(caption = &quot;Overall Proportion of Twitter users by education level&quot;) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;)) # have a nice HTML table</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:bachelor_graduate_prop)Overall Proportion of Twitter users by education level
</caption>
<thead>
<tr>
<th style="text-align:left;">
have a higher educational degree?
</th>
<th style="text-align:right;">
people who use Twitter
</th>
<th style="text-align:right;">
people who don’t use Twitter
</th>
<th style="text-align:right;">
proportion of those who use Twitter
</th>
<th style="text-align:right;">
proportion of those who don’t use Twitter
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
141
</td>
<td style="text-align:right;">
741
</td>
<td style="text-align:right;">
0.1598639
</td>
<td style="text-align:right;">
0.8401361
</td>
</tr>
<tr>
<td style="text-align:left;">
Yes
</td>
<td style="text-align:right;">
114
</td>
<td style="text-align:right;">
375
</td>
<td style="text-align:right;">
0.2331288
</td>
<td style="text-align:right;">
0.7668712
</td>
</tr>
</tbody>
</table>
<p>We see that students with a degree use Twitter more. But how about the confidence intervals?</p>
<p>Using the CI formula for proportions, let’s construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</p>
<pre class="r"><code>bachelor_graduate_formula_ci &lt;- gss_modify %&gt;%
  # drop observations that miss information
  drop_na(c(bachelor_graduate, twitter)) %&gt;% 
  group_by(bachelor_graduate) %&gt;% # group by bachelor_graduate and calculate CIs
  # Confidence Interval = p  +/-  z*(√p(1-p) / n)
  summarise(`proportion of twitter users` = count(twitter == &quot;Yes&quot;) / count(twitter %in% c(&quot;Yes&quot;,&quot;No&quot;)),
            z_critical = qnorm(0.975),
            count = n(),
            se_proportion = sqrt((`proportion of twitter users`*(1-`proportion of twitter users`))/count),
            margin_of_error = z_critical * se_proportion,
            `lower CI bound` = `proportion of twitter users` - margin_of_error,
            `upper CI bound` = `proportion of twitter users` + margin_of_error
  )</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre class="r"><code># print out CIs
bachelor_graduate_formula_ci %&gt;%
  select(bachelor_graduate, `lower CI bound`, `proportion of twitter users`, `upper CI bound`) %&gt;% # only show relevant columns
  rename(`have a higher educational degree?` = bachelor_graduate) %&gt;% # have readable names
  kbl(caption = &quot;Confidence Intervals for Twitter usage&quot;) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;)) # have a nice HTML table</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:bachelor_graduate_ci)Confidence Intervals for Twitter usage
</caption>
<thead>
<tr>
<th style="text-align:left;">
have a higher educational degree?
</th>
<th style="text-align:right;">
lower CI bound
</th>
<th style="text-align:right;">
proportion of twitter users
</th>
<th style="text-align:right;">
upper CI bound
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
0.1356780
</td>
<td style="text-align:right;">
0.1598639
</td>
<td style="text-align:right;">
0.1840499
</td>
</tr>
<tr>
<td style="text-align:left;">
Yes
</td>
<td style="text-align:right;">
0.1956529
</td>
<td style="text-align:right;">
0.2331288
</td>
<td style="text-align:right;">
0.2706048
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># plot CIs
ggplot(bachelor_graduate_formula_ci, aes(y=bachelor_graduate, 
                                         x = `proportion of twitter users`, 
                                         group = bachelor_graduate, 
                                         color=bachelor_graduate)) +
  #draws the means
  geom_point(size = 5) +
  #draws the CI error bars
  geom_errorbar(aes(xmin=`lower CI bound`, xmax=`upper CI bound`), width=.1, size = 2) +
  theme_bw() +
  theme(legend.position = &quot;none&quot;) +
  labs(y = &quot;have a higher educational degree?&quot;,
       x = &quot;Proportion of Twitter users&quot;,
       title = &quot;People with a higher education degree use Twitter more!&quot;)</code></pre>
<p><img src="/blogs/blog8_files/figure-html/bachelor_graduate_ci-1.png" width="672" />
The confidence interval for the proportion of Twitter usage is [13.6%, 18.4%] for those who do not have a degree, vs [19.6%, 27.1%] for thos who have a degree. They do not overlap.</p>
<p>Obviously, more bachelor/graduate student are using Twitter! Are you the majority?</p>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Finally, we also want to have a look at the time people spend on email. How many minutes the respondents spend on email weekly?</p>
<pre class="r"><code>gss &lt;- gss %&gt;% 
  # calculate new variable `email` (notice that either both or non of `emailhr` and `emailmin` are NA!)
  mutate(email = 60*emailhr + emailmin)

email_summary_statistics &lt;- gss %&gt;% 
  summarise(mean = mean(email, na.rm = TRUE), median = median(email, na.rm = TRUE))

# visualise distribution and mean and median
gss %&gt;% 
  ggplot(aes(x = email)) +
  geom_histogram(binwidth = 30) + # binwidth is 30 min
  theme_bw() +
  # add median and mean lines
  geom_vline(aes(xintercept = email_summary_statistics$median, colour = &#39;median&#39;), linetype = 2, size = 1) +
  geom_vline(aes(xintercept = email_summary_statistics$mean, colour = &#39;mean&#39;), linetype = 2, size = 1) +
  # change color of lines
  scale_color_manual(name = NULL, values = c(median = &quot;red&quot;, mean = &quot;blue&quot;)) +
  # show median in legend before mean
  guides(color = guide_legend(reverse = TRUE)) +
  labs(x = &quot;email usage in minutes per week&quot;,
       title = &quot;Distribution of Email Usage&quot;)</code></pre>
<pre><code>## Warning: Removed 1218 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="/blogs/blog8_files/figure-html/email_time-1.png" width="672" /></p>
<p>As shown in the graph, we deal with a right skewed (unbalanced, lopsided) distribution, where the mean is farther out in the long tail than is the median.</p>
<p>Therefore the median is usually preferred to other measures of central tendency when your data set is skewed. The median is a better measure of the typical amount of time Americans spend on email weekly.</p>
<p>How about the confidence interval of email usage? Let’s take a look.</p>
<pre class="r"><code># seed set above

# bootstrap for MEAN email minutes
boot_email &lt;- gss %&gt;%
  # Specify the variable of interest
  specify(response = email) %&gt;%
  
  # Generate a bunch of bootstrap samples
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;%
  
  # Find the median of each sample
  calculate(stat = &quot;mean&quot;)</code></pre>
<pre><code>## Warning: Removed 1218 rows containing missing values.</code></pre>
<pre class="r"><code>percentile_ci &lt;- boot_email %&gt;%
  get_ci(level = 0.95, type = &quot;percentile&quot;)

# print confidence interval
percentile_ci %&gt;% 
  mutate(lower_emailhr = lower_ci %/% 60, 
         lower_emailmin = round(lower_ci %% 60),
         upper_emailhr = upper_ci %/% 60, 
         upper_emailmin = round(upper_ci %% 60),
         `lower bound of average email usage` = paste(lower_emailhr, &quot;hr, &quot;, lower_emailmin, &quot;min&quot;),
         `upper bound of average email usage` = paste(upper_emailhr, &quot;hr, &quot;, upper_emailmin, &quot;min&quot;)) %&gt;% 
  select(`lower bound of average email usage`, `upper bound of average email usage`) %&gt;% # only show relevant columns
  kbl(caption = &quot;Confidence interval for weekly email usage&quot;) %&gt;%
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;hover&quot;, &quot;condensed&quot;, &quot;responsive&quot;)) # have a nice HTML table</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:email_boot_ci)Confidence interval for weekly email usage
</caption>
<thead>
<tr>
<th style="text-align:left;">
lower bound of average email usage
</th>
<th style="text-align:left;">
upper bound of average email usage
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
6 hr, 24 min
</td>
<td style="text-align:left;">
7 hr, 29 min
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># visualise confidence interval
ggplot(boot_email, aes(x = stat)) +
  geom_histogram(bins = 20) +
  labs(title= &quot;Bootstrap distribution of means&quot;) +
  geom_vline(xintercept = percentile_ci$lower_ci, colour = &#39;orange&#39;, linetype = 2, size = 1.2) +
  geom_vline(xintercept = percentile_ci$upper_ci, colour = &#39;orange&#39;, linetype = 2, size = 1.2) +
  theme_bw()</code></pre>
<p><img src="/blogs/blog8_files/figure-html/email_boot_ci-1.png" width="672" /></p>
<p>We can find the confidence interval of weekly time spend on email under 95% is [6 hr 26 min, 7 hr 30 min]. Americans spend around 1 hour per day on email!
However, as we have seen in the distribution plot, this is probably only due to some people spending the whole day emailing, while others only check their mails once in a while.</p>
<p>We would expect a 99% confidence interval to be wider than the interval calculated because to be more confident that the true population value falls within the interval we will need to allow more potential values within the interval.</p>
</div>
</div>
